spring:
  data:
    mongodb:
      uri: "mongodb+srv://xxx:xxx@demo.uskpz.mongodb.net/schema"
      host: localhost
      port: 27017
      database: schema
      username: admin
      password: admin
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG